### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by cblevins** [wcaleb/ricescheduler#2]
I'm getting "The starting date you specified does not exist" for generic syllabus maker. I've tried changing date, year, etc. but keep getting the same message. Thanks!

**Comment by wcaleb** [comment]
I just moved to a new VM and some things broke. Haven't had a chance to 
fix it yet but will try to do it soon.

**Comment by cblevins** [comment]
Thanks Caleb!

**Comment by wcaleb** [comment]
Should be fixed now, let me know if not.
